version: '2.1'

volumes:
  urbit:
  netdatacache:
  netdatalib:
  minio:
  nginx:
services:
  nginx:
    build: ./nginx
    restart: 'unless-stopped'
    ports:
     - "80:80"
     - "443:443"
    command: "nginx -g 'daemon off;'"
  # The following command will start the nginx container and let it idle. That way,
  # we can ssh into the container and shange the nginx configuration files.
  # command: ["tail", "-f", "/dev/null"]
  minio-s3:
    # build: ./minio
    image: minio/minio
    restart: 'unless-stopped'
    environment:
      - MINIO_ROOT_USER=urbitadmin
      - MINIO_ROOT_PASSWORD=urbitadmin
    command: ["server", "/data"]
    volumes: 
      - minio:/data
    ports: 
      - "9000:9000"
    depends_on: 
      - "nginx"
  urbit:
    build: ./urbit
    privileged: false
    restart: 'unless-stopped'
    volumes:
      - urbit:/urbit
    ports:
      - "34343:34343/udp"
      - "8080:8080"
    environment:
      - ENVIRONMENT=PRODUCTION
    depends_on: 
        - "nginx"
  netdata:
    # image: netdata/netdata
    build: ./netdata
    privileged: true
    ports:
      - '19999:19999'
    environment:
      - PGID=989
      - DOCKER_HOST=/var/run/balena-engine.sock
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.supervisor-api: 1
      io.balena.features.sysfs: 1
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
    depends_on: 
      - "nginx"