version: '2.1'

volumes:
  urbit:
  netdatacache:
  netdatalib:
  minio:
  caddy-data:
  caddy-config:
  config:

services:
  anchor:
    build: ./anchor
    privileged: true
    volumes:
      - config:/etc/wireguard
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    labels:
      - io.balena.features.kernel-modules=1
  caddy:
    build: ./caddy
    restart: 'unless-stopped'
    ports:
     - "80:80"
     - "2019:2019"
     - "443:443"
    depends_on: ["minio-s3", "netdata", "urbit"]
    environment:
      - DOMAIN=homeurbit.local
      - PROTOCOL=http
    volumes:
      - config:/config
      - caddy-data:/data
  minio-s3:
    build: ./minio
    restart: 'unless-stopped'
    volumes:
      - minio:/data
    ports:
      - "9000:9000"
      - "9001:9001"
  urbit:
    build: ./urbit
    privileged: false
    restart: 'unless-stopped'
    volumes:
      - urbit:/urbit/piers
      - urbit:/urbit/keys
      - config:/etc
    ports:
      - "34343:34343/udp"
      - "8080:80"
    labels:
      - "io.balena.features.supervisor-api=1"
  netdata:
    build: ./netdata
    privileged: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    ports:
      - "19999:19999"
    labels:
      - "io.balena.features.balena-socket=1"
      - "io.balena.features.procfs=1"
      - "io.balena.features.supervisor-api=1"
      - "io.balena.features.sysfs=1"
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
      - config:/etc
